---
name: lubelogger-fuelio-importer-dev
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: --dry-run
    volumes:
      - ./src:/app/config
      # - ./config:/app/config
