---
name: lubelogger-fuelio-importer
services:
  app:
    image: ghcr.io/tigattack/lubelogger-fuelio-importer:latest
    # Optional flags, e.g. enable dry run mode
    # command: --dry-run
    volumes:
      - ./config:/app/config
