---

# One of 'service' or 'client'
auth_type: service
credentials_file: service_secrets.json

sync_vehicles:
  - fuelio_id: 1
    lubelogger_id: 1

drive_folder_id: 1oegTkfBXlAbRe5Qk_ju7kAJuCFvNem4k

lubelogger_url: https://lubelogger.domain.tld
lubelogger_username: admin
lubelogger_password: password

log_level: info
