---

# The path to your credentials JSON file
credentials_file_path: service_secrets.json

# This list can contain multiple vehicle ID pairs.
sync_vehicles:
  - fuelio_id: 1
    lubelogger_id: 1

drive_folder_id: 1oegTkfBXlAbRe5Qk_ju7kAJuCFvNem4k

lubelogger_url: https://lubelogger.domain.tld
lubelogger_username: admin
lubelogger_password: password

log_level: info
